#!/usr/bin/env bash
# Refresh the shuvam/ snapshot from the canonical sources in backend/.
#
# The files under src/ and tests/ here are copies for handover and review; backend/ is
# where they actually live and run. Without a refresh path the two silently diverge, so
# this script re-copies them and reports what changed. Run it from the repo root.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ ! -d backend/src/qhealth_qml ]; then
  echo "error: run this from a checkout containing backend/src/qhealth_qml" >&2
  exit 1
fi

MODULES=(
  cardiovascular.py
  cardiovascular_cli.py
  prs.py
  multimodal.py
  angiography.py
  ecg.py
  hybrid_qnn.py
  pretrained_encoder.py
)

TESTS=(
  test_cardiovascular.py
  test_prs.py
  test_multimodal.py
  test_angiography.py
  test_ecg.py
)

changed=0

copy_if_different() {
  local source="$1" destination="$2"
  if [ ! -f "$source" ]; then
    echo "  MISSING  $source" >&2
    return
  fi
  if [ ! -f "$destination" ] || ! cmp -s "$source" "$destination"; then
    cp "$source" "$destination"
    echo "  updated  ${destination#"$REPO_ROOT"/}"
    changed=$((changed + 1))
  fi
}

mkdir -p shuvam/src/qhealth_qml shuvam/tests shuvam/results shuvam/profiles

for module in "${MODULES[@]}"; do
  copy_if_different "backend/src/qhealth_qml/$module" "shuvam/src/qhealth_qml/$module"
done

for test in "${TESTS[@]}"; do
  copy_if_different "backend/tests/$test" "shuvam/tests/$test"
done

copy_if_different backend/run_cardiovascular.py shuvam/run_cardiovascular.py
copy_if_different backend/CARDIOVASCULAR_FRAME.md shuvam/CARDIOVASCULAR_FRAME.md
copy_if_different backend/profiles/music_cardiac_death.json shuvam/profiles/music_cardiac_death.json
copy_if_different backend/data/music_cardiac_death/prepare.py shuvam/prepare.py

# Results are regenerated by runs rather than edited, so they are refreshed when present.
for result in backend/runtime/cvd/fit-report.json \
              backend/results/ptbxl-mi-agefix.json \
              backend/results/music-early-detection.json; do
  [ -f "$result" ] && copy_if_different "$result" "shuvam/results/$(basename "$result")"
done

if [ "$changed" -eq 0 ]; then
  echo "snapshot already matches backend/"
else
  echo "refreshed $changed file(s)"
fi

# Guard: dataset payloads must never reach this folder. They are third-party licensed
# and excluded repository-wide; a stray copy here would bypass that.
if find shuvam -type f \( -name '*.csv' -o -name '*.npz' -o -name '*.dat' \
     -o -name '*.hea' -o -name '*.edf' -o -name '*.zip' \) | grep -q .; then
  echo "error: dataset payload found under shuvam/ — remove it before committing" >&2
  exit 1
fi
